### ISSUE TITLE
flowfuse.sh symlink issue

### ISSUE THREAD

**Issue by kaushalkumarjoshi** [FlowFuse/installer#103]
### Current Behavior

On starting the service after installation of flowfuse, it fails.
Changing from
ExecStart=/opt/flowforge/bin/flowfuse.sh
to
ExecStart=/opt/flowforge/bin/flowforge.sh
makes it work.

OS Ubuntu 20.04

### Expected Behavior

The service should start with default setting
ExecStart=/opt/flowforge/bin/flowfuse.sh

### Environment

- FlowFuse version: current
- Node.js version: 20
- npm version: 
- Platform/OS: Ubuntu 20.04
- Browser: Chrome/Edge

**Comment by kaushalkumarjoshi** [comment]
I ran flowforge.sh directly, it worked.

Running flowfuse.sh is not working.

I checked the access and the file is set to executable too.

**Comment by kaushalkumarjoshi** [comment]
After running `journalctl -u flowfuse`
This is the output when `ExecStart=/opt/flowforge/bin/flowforge.sh`

![image](https://github.com/FlowFuse/installer/assets/11587185/345d1511-2c7c-402d-abaa-f0b18ca4230b)

I changed it back to `ExecStart=/opt/flowforge/bin/flowfuse.sh`
Below is the output

![image](https://github.com/FlowFuse/installer/assets/11587185/aeac9479-37f4-443f-a5d7-9f254bca91d3)

**Comment by hardillb** [comment]
Please list the details of how you installed FlowFuse

- Which package did you download from the release page?
- Did you choose to run FlowFuse as the current user or create a new `flowfuse` user?

The package is important because when using the zip file there should be no symlinks.

**Comment by hardillb** [comment]
Using the correct install zip I can't reproduce this, the `flowfuse.sh` script works as intended.

Please answer the earlier questions in full.

**Comment by kaushalkumarjoshi** [comment]
> Please list the details of how you installed FlowFuse
> 
> - Which package did you download from the release page?
> - Did you choose to run FlowFuse as the current user or create a new `flowfuse` user?
> 
> The package is important because when using the zip file there should be no symlinks.


Hi,

I downloaded the flowforge-installer.zip from github and followed the instructions described in the github page.

Also, I am running flowfuse as current user.

**Comment by kaushalkumarjoshi** [comment]
Hi @hardillb,

Reinstalled flowfuse again in a new environment and the issue disappeared.

Thank you for support.
